### ISSUE TITLE
Global Competitiveness Index

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/cpower-viz#62]
## Bugs
- [x] Adjust Height of SVG based on # of flowers
- [x] Set maximum size of flowers
- [x] Adjust position of country label based on # of flowers
- [x] Can't toggle indicators back on after toggling them off
- [x] Petal colors should be permanently assigned to an indicator
- [x] Tooltip Content doesn't change when country data changes

## Todos
- [x] Indicator Selection
- [x] Legend
  - [x] Add size annotation
  - [x] Remove petal when indicator is unselected
  - [x] Color list item bubbles by pillar
- [x] Line Chart
  - [x] Create line chart with selected country data that shows selected indicator data per country over time
  - [x] X-axis: Years
  - [x] Y-Axis: Domain of indicator data for selected countries
    - [x] Set minimum step for ticks
  - [x] Color: By country
    - [x] Get colors from Tucker
    - [x] China should always be same color
  - [x] Legend with country names & corresponding color
  - [x] When the line chart is activated, highlight the corresponding petals
  - [x] Updating country selection should update line chart
  - [x] Updating selected indicators should update line chart
    - [x] If selected pillar is toggled off, hide lines on line chart
    - [x] Remove active styles from petals if the active pillar was toggled off
  - [x] Initial View: Need instruction text/overlay
  - [x] When data is missing, show line segments instead (use d3-chunked plugin for this)
  - [x] If possible, change years on line chart to "07-08"
  - [x] Don't show default pillar, just X axis and countries
  - [x] Position country names horizontally below chart
- [x] Change Clear selection button style
- [x] Change Update Button appearance when selection has changed
- [x] Add Tooltips to Petals
  - [x] Country Name
  - [x] Start & End Year
  - [x] Overall Rank
  - [x] Indicator Name
  - [x] Indicator Score
  - [x] Indicator Rank
- [x] Add Tooltips to Line Chart
  - [x] Country Name: Indicator Score
  - [x] Start & End Year
  - [x] Indicator Name
- [x] Instructions
- [x] Flower Petal transitions
- [x] If no data is available for a country, show text warning instead of flower
- [x] Change "Select Countries" to "Select Economies"
- [x] Clicking on legend petals should do the same thing as clicking on regular flowers
- [x] Hovering on legend petal should highlight all petals with same pillar
- [x] Mobile
  - [x] Max of 2 Countries
  - [x] Disable Line Chart

## Questions
1. When filtering the indicators, should the legend also adjust to only show the available indicators? If not, then we should make the unavailable petals more transparent. **Remove petal completely**
2. Layout of the legend
3. How does the user remove the line chart from the screen? **They don't. The line chart is always visible.**
4. What to do if selected country doesn't have data available for the selected indicator? **Show text warning instead of flower**
5. Should the line chart have a guide line and a single tooltip like the [Military Diplomacy Chart](https://chinapower.csis.org/china-military-diplomacy/) **Yes**
